spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bank-database:3306/bank?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456



